import { Difficulty } from "../types";
import { PythonExerciseBlueprint, PythonTopicId } from "../pythonTypes";

// Playful and applied topics for Python Lab.
//
// GIOCHI: these call input(), so each ships `mockInputs` -- the scripted answers
// the browser feeds to the mocked input(). Real input(prompt) writes the prompt
// to stdout with no newline, so the prompts are part of the expected output; the
// mock in pythonService mirrors that exactly. `random` is always seeded, because
// the exercise is graded on its output and an unseeded game would differ on
// every run.
//
// DEEP LEARNING: built on NumPy, not PyTorch. torch has no WebAssembly build and
// micropip installs pure-Python wheels only, so `import torch` cannot work in the
// browser. These teach the maths PyTorch performs -- forward pass, loss, chain
// rule, gradient descent, momentum, dropout -- and every explanation names the
// PyTorch call that does the same thing (nn.Linear, nn.MSELoss, loss.backward,
// optimizer.step, model.eval), so the concepts transfer directly to torch.
export const PLAYGROUND_EXERCISES: Record<string, Record<Difficulty, PythonExerciseBlueprint[]>> = {

  [PythonTopicId.Games]: {
    [Difficulty.Easy]: [
      {
        titleTemplate: "Lancio del dado",
        descTemplate: "Lancia un dado a 6 facce con il seme casuale fissato a 42 e stampa il risultato.",
        starterCode: "import random\nrandom.seed(42)\n",
        solutionCode: "import random\nrandom.seed(42)\nprint(random.randint(1, 6))",
        expectedOutput: "6",
        hints: ["randint(a, b) include entrambi gli estremi", "Il seme fissato rende il risultato ripetibile"],
        explanation: "randint(1, 6) sceglie un intero fra 1 e 6 inclusi. Fissare il seme serve qui perché l'esercizio va corretto in automatico: senza, ogni esecuzione darebbe un numero diverso.",
        brokenCode: "import random\nrandom.seed(42)\nprint(random.randint(1, 7))",
        debugHint: "randint include l'estremo superiore: con 7 usciresti dal dado.",
      },
      {
        titleTemplate: "Testa o croce",
        descTemplate: "Con il seme fissato a 7, scegli casualmente fra testa e croce e stampa la scelta.",
        starterCode: "import random\nrandom.seed(7)\n",
        solutionCode: "import random\nrandom.seed(7)\nprint(random.choice(['testa', 'croce']))",
        expectedOutput: "croce",
        hints: ["choice() pesca un elemento da una sequenza", "La lista va passata come unico argomento"],
        explanation: "choice pesca un elemento a caso dalla lista. E' la funzione che userai per far scegliere il computer nei giochi a turni.",
        brokenCode: "import random\nrandom.seed(7)\nprint(random.choice('testa', 'croce'))",
        debugHint: "choice vuole UNA sequenza: passa una lista, non due argomenti separati.",
      },
      {
        titleTemplate: "Benvenuto personalizzato",
        descTemplate: "Chiedi il nome al giocatore e salutalo. Il giocatore risponde 'Simone'.",
        starterCode: "nome = input('Come ti chiami? ')\n",
        solutionCode: "nome = input('Come ti chiami? ')\nprint(f'Benvenuto, {nome}!')",
        expectedOutput: "Come ti chiami? Benvenuto, Simone!",
        hints: ["input() restituisce sempre una stringa", "La f-string inserisce la variabile nel testo"],
        explanation: "input mostra il prompt e restituisce quello che l'utente scrive. Il prompt finisce nell'output, quindi compare anche nel risultato atteso.",
        brokenCode: "nome = input('Come ti chiami? ')\nprint('Benvenuto, nome!')",
        debugHint: "Senza f davanti alle virgolette la variabile non viene sostituita: stampi la parola 'nome'.",
        mockInputs: ["Simone"],
      },
      {
        titleTemplate: "Scelta valida o no",
        descTemplate: "Chiedi una scelta fra carta, forbici e sasso e verifica che sia valida. Il giocatore scrive 'banana'.",
        starterCode: "SCELTE = ['carta', 'forbici', 'sasso']\n",
        solutionCode: "SCELTE = ['carta', 'forbici', 'sasso']\nscelta = input('Scegli: ').lower().strip()\nif scelta not in SCELTE:\n    print('Scelta non valida')\nelse:\n    print('Hai scelto', scelta)",
        expectedOutput: "Scegli: Scelta non valida",
        hints: ["L'operatore in verifica l'appartenenza a una lista", "lower() e strip() ripuliscono quello che l'utente digita"],
        explanation: "Validare l'ingresso prima di usarlo evita che il resto del gioco lavori su un valore senza senso. lower e strip perdonano maiuscole e spazi di troppo, che sono l'errore di battitura più comune.",
        brokenCode: "SCELTE = ['carta', 'forbici', 'sasso']\nscelta = input('Scegli: ')\nif scelta not in SCELTE:\n    print('Scelta non valida')\nelse:\n    print('Hai scelto', scelta)",
        debugHint: "Senza lower() una risposta come 'Carta' con la maiuscola verrebbe rifiutata.",
        mockInputs: ["banana"],
      },
      {
        titleTemplate: "Chi vince a carta forbici sasso",
        descTemplate: "Date due scelte già fissate (carta contro sasso), stampa chi vince.",
        starterCode: "giocatore = 'carta'\ncomputer = 'sasso'\n",
        solutionCode: "giocatore = 'carta'\ncomputer = 'sasso'\nif giocatore == computer:\n    print('Pareggio')\nelif (giocatore == 'carta' and computer == 'sasso') or (giocatore == 'forbici' and computer == 'carta') or (giocatore == 'sasso' and computer == 'forbici'):\n    print('Vince il giocatore')\nelse:\n    print('Vince il computer')",
        expectedOutput: "Vince il giocatore",
        hints: ["Le combinazioni vincenti del giocatore sono solo tre", "Il pareggio va controllato per primo"],
        explanation: "Le tre condizioni vincenti si scrivono una volta sola con degli or. Controllare il pareggio per primo semplifica il resto: dopo quel controllo sai già che le scelte sono diverse.",
        brokenCode: "giocatore = 'carta'\ncomputer = 'sasso'\nif giocatore == 'carta' and computer == 'sasso':\n    print('Vince il giocatore')\nelse:\n    print('Vince il computer')",
        debugHint: "Mancano le altre due combinazioni vincenti e il caso di pareggio.",
      },
      {
        titleTemplate: "Pari o dispari",
        descTemplate: "Il giocatore dichiara 'pari' e mostra 3 dita, il computer ne mostra 2. Stampa chi ha indovinato.",
        starterCode: "dichiarazione = 'pari'\ndita_giocatore = 3\ndita_computer = 2\n",
        solutionCode: "dichiarazione = 'pari'\ndita_giocatore = 3\ndita_computer = 2\ntotale = dita_giocatore + dita_computer\nesito = 'pari' if totale % 2 == 0 else 'dispari'\nprint(f'Totale {totale}, esito {esito}')\nprint('Vince il giocatore' if esito == dichiarazione else 'Vince il computer')",
        expectedOutput: "Totale 5, esito dispari\nVince il computer",
        hints: ["Il resto della divisione per 2 dice se un numero è pari", "L'espressione condizionale sta su una riga sola"],
        explanation: "Il modulo 2 distingue pari da dispari, e l'espressione condizionale traduce quel booleano in una parola confrontabile con la dichiarazione del giocatore.",
        brokenCode: "dichiarazione = 'pari'\ntotale = 3 + 2\nprint('Vince il giocatore' if totale % 2 == 0 else 'Vince il computer')",
        debugHint: "Funziona solo se il giocatore dichiara 'pari': non tiene conto della dichiarazione.",
      },
      {
        titleTemplate: "Estrai una carta",
        descTemplate: "Con il seme a 3, pesca un valore e un seme da un mazzo e stampa la carta.",
        starterCode: "import random\nrandom.seed(3)\n",
        solutionCode: "import random\nrandom.seed(3)\nVALORI = ['asso', 'due', 'tre', 'donna', 're']\nSEMI = ['cuori', 'picche']\nprint(f'{random.choice(VALORI)} di {random.choice(SEMI)}')",
        expectedOutput: "due di cuori",
        hints: ["Servono due choice: uno per il valore, uno per il seme", "L'ordine delle chiamate conta per il risultato"],
        explanation: "Due estrazioni indipendenti compongono la carta. Con il seme fissato la sequenza di numeri casuali è sempre la stessa, quindi l'ordine in cui chiami choice determina il risultato.",
        brokenCode: "import random\nrandom.seed(3)\nVALORI = ['asso', 'due', 'tre', 'donna', 're']\nSEMI = ['cuori', 'picche']\nprint(f'{random.choice(SEMI)} di {random.choice(VALORI)}')",
        debugHint: "Le due estrazioni sono invertite: esce 'cuori di asso'.",
      },
      {
        titleTemplate: "Indovina il numero, un tentativo",
        descTemplate: "Il numero segreto è 7 e il giocatore prova con 5. Di' se è troppo basso, troppo alto o corretto.",
        starterCode: "segreto = 7\n",
        solutionCode: "segreto = 7\ntentativo = int(input('Indovina: '))\nif tentativo == segreto:\n    print('Indovinato!')\nelif tentativo < segreto:\n    print('Troppo basso')\nelse:\n    print('Troppo alto')",
        expectedOutput: "Indovina: Troppo basso",
        hints: ["input() torna una stringa: convertila con int()", "Confronta prima l'uguaglianza"],
        explanation: "int converte la stringa in numero, altrimenti il confronto sarebbe fra tipi diversi. Le tre risposte coprono ogni caso, quindi il giocatore ha sempre un riscontro utile.",
        brokenCode: "segreto = 7\ntentativo = input('Indovina: ')\nif tentativo < segreto:\n    print('Troppo basso')",
        debugHint: "TypeError: stai confrontando una stringa con un numero. Manca int().",
        mockInputs: ["5"],
      },
    ],
    [Difficulty.Medium]: [
      {
        titleTemplate: "Carta forbici sasso 2.0: più partite",
        descTemplate: "Il giocatore si chiama Anna e vuole 2 partite, giocando 'carta' e poi 'sasso'. Seme fissato a 1.",
        starterCode: "import random\nrandom.seed(1)\nSCELTE = ['carta', 'forbici', 'sasso']\n",
        solutionCode: "import random\nrandom.seed(1)\nSCELTE = ['carta', 'forbici', 'sasso']\nnome = input('Nome: ')\npartite = int(input('Quante partite? '))\nfor n in range(partite):\n    scelta = input(f'Partita {n+1} - scegli: ').lower().strip()\n    if scelta not in SCELTE:\n        print('Scelta non valida')\n        continue\n    computer = random.choice(SCELTE)\n    print(f'Il computer ha scelto: {computer}')\n    if scelta == computer:\n        print('Pareggio')\n    elif (scelta == 'carta' and computer == 'sasso') or (scelta == 'forbici' and computer == 'carta') or (scelta == 'sasso' and computer == 'forbici'):\n        print(f'{nome} vince')\n    else:\n        print('Computer vince')",
        expectedOutput: "Nome: Quante partite? Partita 1 - scegli: Il computer ha scelto: carta\nPareggio\nPartita 2 - scegli: Il computer ha scelto: sasso\nPareggio",
        hints: ["Il ciclo for ripete la partita quante volte serve", "continue salta al giro dopo senza uscire dal ciclo"],
        explanation: "Il ciclo trasforma una partita singola in una serie. continue è la scelta giusta per la scelta non valida: salta solo quel turno invece di interrompere tutto il gioco.",
        brokenCode: "import random\nrandom.seed(1)\nSCELTE = ['carta', 'forbici', 'sasso']\nnome = input('Nome: ')\npartite = input('Quante partite? ')\nfor n in range(partite):\n    print(n)",
        debugHint: "TypeError: range vuole un intero, ma input() restituisce una stringa.",
        mockInputs: ["Anna", "2", "carta", "sasso"],
      },
      {
        titleTemplate: "Carta forbici sasso 3.0: punteggio",
        descTemplate: "Anna gioca 3 partite (carta, sasso, forbici) e vuole il punteggio a ogni turno e il vincitore finale. Seme a 5.",
        starterCode: "import random\nrandom.seed(5)\nSCELTE = ['carta', 'forbici', 'sasso']\n",
        solutionCode: "import random\nrandom.seed(5)\nSCELTE = ['carta', 'forbici', 'sasso']\nnome = input('Nome: ')\npartite = int(input('Quante partite? '))\npunti_g = 0\npunti_c = 0\nfor n in range(partite):\n    scelta = input(f'Partita {n+1} - scegli: ').lower().strip()\n    computer = random.choice(SCELTE)\n    if scelta == computer:\n        esito = 'Pareggio'\n    elif (scelta == 'carta' and computer == 'sasso') or (scelta == 'forbici' and computer == 'carta') or (scelta == 'sasso' and computer == 'forbici'):\n        esito = f'{nome} vince'\n        punti_g += 1\n    else:\n        esito = 'Computer vince'\n        punti_c += 1\n    print(f'{computer} -> {esito}')\n    print(f'Punteggio: {nome} {punti_g} - Computer {punti_c}')\nif punti_g > punti_c:\n    print(f'{nome} e\\' il vincitore finale!')\nelif punti_g < punti_c:\n    print('Il computer e\\' il vincitore finale!')\nelse:\n    print('Pareggio finale!')",
        expectedOutput: "Nome: Quante partite? Partita 1 - scegli: sasso -> Anna vince\nPunteggio: Anna 1 - Computer 0\nPartita 2 - scegli: forbici -> Anna vince\nPunteggio: Anna 2 - Computer 0\nPartita 3 - scegli: sasso -> Computer vince\nPunteggio: Anna 2 - Computer 1\nAnna e' il vincitore finale!",
        hints: ["I due contatori vanno inizializzati PRIMA del ciclo", "Il confronto finale va dopo il ciclo, non dentro"],
        explanation: "I contatori vivono fuori dal ciclo, altrimenti si azzererebbero a ogni turno. Il verdetto finale sta dopo il ciclo, quando entrambi i punteggi sono definitivi.",
        brokenCode: "import random\nrandom.seed(5)\nSCELTE = ['carta', 'forbici', 'sasso']\nfor n in range(3):\n    punti_g = 0\n    punti_g += 1\n    print(punti_g)",
        debugHint: "Il contatore viene azzerato dentro il ciclo, quindi resta sempre 1.",
        mockInputs: ["Anna", "3", "carta", "sasso", "forbici"],
      },
      {
        titleTemplate: "Indovina il numero a tentativi",
        descTemplate: "Il segreto è 7. Il giocatore prova 3, poi 9, poi 7. Dai un suggerimento a ogni tentativo e conta i tentativi.",
        starterCode: "segreto = 7\n",
        solutionCode: "segreto = 7\ntentativi = 0\nwhile True:\n    n = int(input('Indovina: '))\n    tentativi += 1\n    if n == segreto:\n        print(f'Indovinato in {tentativi} tentativi')\n        break\n    print('Troppo basso' if n < segreto else 'Troppo alto')",
        expectedOutput: "Indovina: Troppo basso\nIndovina: Troppo alto\nIndovina: Indovinato in 3 tentativi",
        hints: ["while True con break è il modo naturale per 'ripeti finche' non indovina'", "Il contatore va incrementato a ogni giro"],
        explanation: "while True ripete senza una condizione nota in anticipo e break esce appena il numero è corretto. E' il pattern standard quando non sai quanti giri serviranno.",
        brokenCode: "segreto = 7\ntentativi = 0\nwhile True:\n    n = int(input('Indovina: '))\n    if n == segreto:\n        print(f'Indovinato in {tentativi} tentativi')\n        break\n    print('Troppo basso' if n < segreto else 'Troppo alto')",
        debugHint: "Il contatore non viene mai incrementato: stampa sempre 0 tentativi.",
        mockInputs: ["3", "9", "7"],
      },
      {
        titleTemplate: "Impiccato: lettera indovinata",
        descTemplate: "La parola è 'python' e il giocatore prova la lettera 'o'. Mostra la parola con i trattini e le lettere trovate.",
        starterCode: "parola = 'python'\ntrovate = set()\n",
        solutionCode: "parola = 'python'\ntrovate = set()\nlettera = input('Lettera: ').lower().strip()\nif lettera in parola:\n    trovate.add(lettera)\n    print('Giusto!')\nelse:\n    print('Sbagliato!')\nprint(''.join(c if c in trovate else '_' for c in parola))",
        expectedOutput: "Lettera: Giusto!\n____o_",
        hints: ["Un set tiene le lettere già scoperte", "join con una comprensione ricostruisce la parola mascherata"],
        explanation: "Il set delle lettere trovate è l'unico stato che serve: la maschera si ricalcola ogni volta scorrendo la parola e decidendo carattere per carattere se mostrarlo.",
        brokenCode: "parola = 'python'\ntrovate = set()\nlettera = input('Lettera: ')\nif lettera in parola:\n    trovate.add(lettera)\nprint(''.join(c if c in trovate else '_' for c in trovate))",
        debugHint: "Il ciclo scorre le lettere trovate invece della parola: la maschera esce lunga quanto le lettere indovinate.",
        mockInputs: ["o"],
      },
      {
        titleTemplate: "Sfida ai dadi",
        descTemplate: "Giocatore e computer lanciano 3 dadi ciascuno con seme 11. Somma i punteggi e dichiara il vincitore.",
        starterCode: "import random\nrandom.seed(11)\n",
        solutionCode: "import random\nrandom.seed(11)\ngiocatore = sum(random.randint(1, 6) for _ in range(3))\ncomputer = sum(random.randint(1, 6) for _ in range(3))\nprint(f'Giocatore {giocatore} - Computer {computer}')\nif giocatore > computer:\n    print('Vince il giocatore')\nelif giocatore < computer:\n    print('Vince il computer')\nelse:\n    print('Pareggio')",
        expectedOutput: "Giocatore 13 - Computer 14\nVince il computer",
        hints: ["sum con una generator expression evita il ciclo esplicito", "L'underscore si usa quando l'indice non serve"],
        explanation: "sum di una generator expression somma i tre lanci senza accumulatore manuale. L'underscore segnala a chi legge che la variabile del ciclo non viene usata.",
        brokenCode: "import random\nrandom.seed(11)\ngiocatore = random.randint(1, 6) * 3\ncomputer = sum(random.randint(1, 6) for _ in range(3))\nprint(f'Giocatore {giocatore} - Computer {computer}')",
        debugHint: "Moltiplicare un lancio per 3 non è come lanciare tre dadi: i risultati possibili sono solo multipli di 3.",
      },
      {
        titleTemplate: "Tris: riga vincente",
        descTemplate: "Data la griglia [['X','X','X'],['O','O',' '],[' ',' ','O']], di' se una riga è completa e con quale simbolo.",
        starterCode: "griglia = [['X','X','X'],['O','O',' '],[' ',' ','O']]\n",
        solutionCode: "griglia = [['X','X','X'],['O','O',' '],[' ',' ','O']]\nvincitore = None\nfor riga in griglia:\n    if riga[0] != ' ' and riga[0] == riga[1] == riga[2]:\n        vincitore = riga[0]\n        break\nprint(f'Vince {vincitore}' if vincitore else 'Nessun vincitore')",
        expectedOutput: "Vince X",
        hints: ["I confronti a catena permettono riga[0] == riga[1] == riga[2]", "Escludi la casella vuota, altrimenti tre spazi risultano vincenti"],
        explanation: "Il confronto a catena verifica che i tre simboli coincidano, e il controllo sullo spazio evita che una riga vuota venga letta come vittoria: è l'errore più comune in questo esercizio.",
        brokenCode: "griglia = [['X','X','X'],['O','O',' '],[' ',' ','O']]\nfor riga in griglia:\n    if riga[0] == riga[1] == riga[2]:\n        print(f'Vince {riga[0]}')\n        break",
        debugHint: "Senza escludere lo spazio, una riga di tre caselle vuote verrebbe dichiarata vincente.",
      },
      {
        titleTemplate: "Quiz a punti",
        descTemplate: "Poni 2 domande di matematica. Il giocatore risponde 4 e poi 10 (la seconda è sbagliata). Stampa il punteggio finale.",
        starterCode: "domande = [('2+2', '4'), ('3*4', '12')]\n",
        solutionCode: "domande = [('2+2', '4'), ('3*4', '12')]\npunti = 0\nfor testo, giusta in domande:\n    risposta = input(f'{testo} = ').strip()\n    if risposta == giusta:\n        punti += 1\n        print('Giusto')\n    else:\n        print(f'Sbagliato, era {giusta}')\nprint(f'Punteggio: {punti}/{len(domande)}')",
        expectedOutput: "2+2 = Giusto\n3*4 = Sbagliato, era 12\nPunteggio: 1/2",
        hints: ["Una lista di tuple tiene insieme domanda e risposta", "L'unpacking nel for separa i due valori"],
        explanation: "Tenere domanda e risposta nella stessa tupla evita due liste da mantenere allineate. L'unpacking nel for le separa in due variabili leggibili.",
        brokenCode: "domande = [('2+2', '4'), ('3*4', '12')]\npunti = 0\nfor testo, giusta in domande:\n    risposta = input(f'{testo} = ')\n    if risposta == giusta:\n        punti += 1\nprint(f'Punteggio: {punti}/{len(domande)}')",
        debugHint: "Il giocatore non riceve nessun riscontro sulle singole risposte.",
        mockInputs: ["4", "10"],
      },
    ],
    [Difficulty.Hard]: [
      {
        titleTemplate: "Carta forbici sasso 4.0: modalità invincibile",
        descTemplate: "Anna attiva la modalità invincibile e gioca 2 partite (carta, sasso): il computer deve sempre perdere. Seme a 2.",
        starterCode: "SCELTE = ['carta', 'forbici', 'sasso']\nPERDENTE = {'carta': 'sasso', 'forbici': 'carta', 'sasso': 'forbici'}\n",
        solutionCode: "import random\nrandom.seed(2)\nSCELTE = ['carta', 'forbici', 'sasso']\nPERDENTE = {'carta': 'sasso', 'forbici': 'carta', 'sasso': 'forbici'}\nnome = input('Nome: ')\ninvincibile = input('Modalita\\' invincibile? (si/no) ').lower().strip() == 'si'\npartite = int(input('Quante partite? '))\nfor n in range(partite):\n    scelta = input(f'Partita {n+1} - scegli: ').lower().strip()\n    computer = PERDENTE[scelta] if invincibile else random.choice(SCELTE)\n    print(f'Il computer ha scelto: {computer}')\n    print(f'{nome} vince')",
        expectedOutput: "Nome: Modalita' invincibile? (si/no) Quante partite? Partita 1 - scegli: Il computer ha scelto: sasso\nAnna vince\nPartita 2 - scegli: Il computer ha scelto: forbici\nAnna vince",
        hints: ["Un dizionario mappa ogni scelta a quella che le perde contro", "L'espressione condizionale sceglie fra la mossa truccata e quella casuale"],
        explanation: "Il dizionario PERDENTE codifica le regole al contrario: data la mossa del giocatore restituisce quella che perde. In modalità invincibile il computer la usa al posto di choice, quindi il giocatore vince sempre senza toccare la logica del confronto.",
        brokenCode: "SCELTE = ['carta', 'forbici', 'sasso']\nPERDENTE = {'carta': 'sasso', 'forbici': 'carta', 'sasso': 'forbici'}\nscelta = 'carta'\ncomputer = PERDENTE['sasso']\nprint(computer)",
        debugHint: "Il dizionario va interrogato con la scelta DEL GIOCATORE, non con un valore fisso.",
        mockInputs: ["Anna", "si", "2", "carta", "sasso"],
      },
      {
        titleTemplate: "Tris completo",
        descTemplate: "Data la griglia [['X','O','O'],['O','X','O'],['O','O','X']], controlla righe, colonne e diagonali.",
        starterCode: "griglia = [['X','O','O'],['O','X','O'],['O','O','X']]\n",
        solutionCode: "griglia = [['X','O','O'],['O','X','O'],['O','O','X']]\nlinee = []\nlinee.extend(griglia)\nlinee.extend([[griglia[r][c] for r in range(3)] for c in range(3)])\nlinee.append([griglia[i][i] for i in range(3)])\nlinee.append([griglia[i][2-i] for i in range(3)])\nvincitore = None\nfor linea in linee:\n    if linea[0] != ' ' and linea[0] == linea[1] == linea[2]:\n        vincitore = linea[0]\n        break\nprint(f'Vince {vincitore}' if vincitore else 'Nessun vincitore')",
        expectedOutput: "Vince X",
        hints: ["Costruisci tutte le 8 linee, poi applica un controllo solo", "La diagonale secondaria usa l'indice 2-i"],
        explanation: "Raccogliere righe, colonne e diagonali in un'unica lista di linee riduce il problema a un solo controllo ripetuto otto volte, invece di tre blocchi di codice quasi uguali.",
        brokenCode: "griglia = [['X','O','O'],['O','X','O'],['O','O','X']]\nlinee = list(griglia)\nlinee.append([griglia[i][i] for i in range(3)])\nfor linea in linee:\n    if linea[0] != ' ' and linea[0] == linea[1] == linea[2]:\n        print(f'Vince {linea[0]}')",
        debugHint: "Mancano le colonne e la diagonale secondaria: alcune vittorie non vengono viste.",
      },
      {
        titleTemplate: "Blackjack: valore della mano",
        descTemplate: "Calcola il valore della mano ['asso', 're', 'asso'], dove l'asso vale 11 o 1 secondo convenienza.",
        starterCode: "mano = ['asso', 're', 'asso']\nVALORI = {'due': 2, 'tre': 3, 'dieci': 10, 'donna': 10, 're': 10, 'asso': 11}\n",
        solutionCode: "mano = ['asso', 're', 'asso']\nVALORI = {'due': 2, 'tre': 3, 'dieci': 10, 'donna': 10, 're': 10, 'asso': 11}\ntotale = sum(VALORI[c] for c in mano)\nassi = mano.count('asso')\nwhile totale > 21 and assi > 0:\n    totale -= 10\n    assi -= 1\nprint(totale)",
        expectedOutput: "12",
        hints: ["Conta prima tutti gli assi come 11, poi correggi", "Ogni asso declassato toglie 10 al totale"],
        explanation: "Il trucco è contare tutti gli assi come 11 e poi toglierne 10 uno alla volta finche' il totale rientra: così si ottiene sempre il valore più alto che non sballa, che è la regola del blackjack.",
        brokenCode: "mano = ['asso', 're', 'asso']\nVALORI = {'due': 2, 'tre': 3, 'dieci': 10, 'donna': 10, 're': 10, 'asso': 11}\ntotale = sum(VALORI[c] for c in mano)\nif totale > 21:\n    totale -= 10\nprint(totale)",
        debugHint: "Un solo if declassa un asso solo: con due assi il totale resta sopra 21.",
      },
      {
        titleTemplate: "Impiccato con vite",
        descTemplate: "La parola è 'ciao' e il giocatore ha 3 vite. Prova le lettere c, z, a, o. Stampa lo stato finale.",
        starterCode: "parola = 'ciao'\n",
        solutionCode: "parola = 'ciao'\nvite = 3\ntrovate = set()\nfor _ in range(4):\n    l = input('Lettera: ').lower().strip()\n    if l in parola:\n        trovate.add(l)\n    else:\n        vite -= 1\n    print(f\"{''.join(c if c in trovate else '_' for c in parola)} (vite: {vite})\")\nprint('Parola completata!' if set(parola) <= trovate else 'Hai perso')",
        expectedOutput: "Lettera: c___ (vite: 3)\nLettera: c___ (vite: 2)\nLettera: c_a_ (vite: 2)\nLettera: c_ao (vite: 2)\nHai perso",
        hints: ["Le vite calano solo sugli errori", "L'operatore <= fra set verifica il sottoinsieme"],
        explanation: "set(parola) <= trovate chiede se ogni lettera della parola è stata scoperta: è il test di sottoinsieme, più diretto che contare le lettere una a una.",
        brokenCode: "parola = 'ciao'\nvite = 3\ntrovate = set()\nfor _ in range(4):\n    l = input('Lettera: ')\n    trovate.add(l)\n    vite -= 1\n    print(f\"{''.join(c if c in trovate else '_' for c in parola)} (vite: {vite})\")",
        debugHint: "Le vite calano anche quando la lettera è giusta, e le lettere sbagliate finiscono fra quelle trovate.",
        mockInputs: ["c", "z", "a", "o"],
      },
      {
        titleTemplate: "Nim: la mossa vincente",
        descTemplate: "Restano 7 fiammiferi e si possono prendere da 1 a 3. Calcola quanti prenderne per vincere sicuramente.",
        starterCode: "fiammiferi = 7\nMAX_PRESA = 3\n",
        solutionCode: "fiammiferi = 7\nMAX_PRESA = 3\nresto = fiammiferi % (MAX_PRESA + 1)\nif resto == 0:\n    print('Nessuna mossa vincente, prendi 1')\nelse:\n    print(f'Prendi {resto}')",
        expectedOutput: "Prendi 3",
        hints: ["La strategia si basa sul resto della divisione per (max + 1)", "Se il resto è zero sei in posizione perdente"],
        explanation: "Lasciando all'avversario un multiplo di 4 puoi sempre ripristinarlo alla mossa dopo, quindi vinci. Il resto della divisione per 4 dice esattamente quanti fiammiferi prendere per arrivarci.",
        brokenCode: "fiammiferi = 7\nMAX_PRESA = 3\nprint(f'Prendi {fiammiferi % MAX_PRESA}')",
        debugHint: "Il divisore giusto è MAX_PRESA + 1, non MAX_PRESA: con 7 fiammiferi la mossa corretta è 3, non 1.",
      },
      {
        titleTemplate: "Forza 4: quattro in colonna",
        descTemplate: "Nella colonna ['R','G','G','G','G','R'] verifica se ci sono quattro pedine uguali di fila.",
        starterCode: "colonna = ['R','G','G','G','G','R']\n",
        solutionCode: "colonna = ['R','G','G','G','G','R']\nvincitore = None\nfor i in range(len(colonna) - 3):\n    finestra = colonna[i:i+4]\n    if finestra[0] != ' ' and len(set(finestra)) == 1:\n        vincitore = finestra[0]\n        break\nprint(f'Vince {vincitore}' if vincitore else 'Nessun vincitore')",
        expectedOutput: "Vince G",
        hints: ["Fai scorrere una finestra di 4 elementi", "Se il set della finestra ha un solo elemento, sono tutti uguali"],
        explanation: "La finestra scorrevole confronta quattro posizioni per volta e si ferma a len-3 per non uscire dalla lista. set(finestra) con un solo elemento è il modo più compatto di dire che sono tutti uguali.",
        brokenCode: "colonna = ['R','G','G','G','G','R']\nfor i in range(len(colonna)):\n    finestra = colonna[i:i+4]\n    if len(set(finestra)) == 1:\n        print(f'Vince {finestra[0]}')\n        break",
        debugHint: "Il ciclo va oltre il limite: le ultime finestre sono più corte di 4 e una finestra di 1 elemento risulta 'tutta uguale'.",
      },
      {
        titleTemplate: "Simulazione di mille partite",
        descTemplate: "Simula 1000 partite di carta forbici sasso con scelte casuali (seme 42) e stampa quante ne vince il giocatore.",
        starterCode: "import random\nrandom.seed(42)\nSCELTE = ['carta', 'forbici', 'sasso']\n",
        solutionCode: "import random\nrandom.seed(42)\nSCELTE = ['carta', 'forbici', 'sasso']\nBATTE = {'carta': 'sasso', 'forbici': 'carta', 'sasso': 'forbici'}\nvittorie = 0\nfor _ in range(1000):\n    g = random.choice(SCELTE)\n    c = random.choice(SCELTE)\n    if BATTE[g] == c:\n        vittorie += 1\nprint(vittorie)",
        expectedOutput: "335",
        hints: ["Un dizionario batte-chi evita la catena di or", "Con scelte casuali la percentuale attesa è circa un terzo"],
        explanation: "BATTE[g] == c sostituisce tre condizioni con una lettura di dizionario. Su mille partite casuali le vittorie si assestano vicino a 333, cioe' un terzo: è la verifica che la simulazione sia corretta.",
        brokenCode: "import random\nrandom.seed(42)\nSCELTE = ['carta', 'forbici', 'sasso']\nBATTE = {'carta': 'sasso', 'forbici': 'carta', 'sasso': 'forbici'}\nvittorie = 0\nfor _ in range(1000):\n    g = random.choice(SCELTE)\n    c = random.choice(SCELTE)\n    if BATTE[c] == g:\n        vittorie += 1\nprint(vittorie)",
        debugHint: "Il confronto è invertito: così conti le vittorie del computer.",
      },
    ],
  },

  [PythonTopicId.Forecasting]: {
    [Difficulty.Easy]: [
      {
        titleTemplate: "Previsione naive",
        descTemplate: "La serie è [10, 12, 15, 14]. La previsione naive per il prossimo periodo è l'ultimo valore osservato.",
        starterCode: "serie = [10, 12, 15, 14]\n",
        solutionCode: "serie = [10, 12, 15, 14]\nprint(serie[-1])",
        expectedOutput: "14",
        hints: ["L'indice -1 prende l'ultimo elemento", "La naive non fa calcoli: ripete l'ultimo valore"],
        explanation: "La previsione naive usa l'ultimo valore osservato come stima del prossimo. Sembra banale ma è il riferimento con cui si confronta ogni modello: se un modello complesso non la batte, non serve.",
        brokenCode: "serie = [10, 12, 15, 14]\nprint(serie[0])",
        debugHint: "serie[0] è il PRIMO valore: la naive usa l'ultimo, cioe' serie[-1].",
      },
      {
        titleTemplate: "Media come previsione",
        descTemplate: "Prevedi il prossimo valore di [4, 6, 8, 10] con la media di tutta la serie, arrotondata a 2 decimali.",
        starterCode: "serie = [4, 6, 8, 10]\n",
        solutionCode: "serie = [4, 6, 8, 10]\nprint(round(sum(serie) / len(serie), 2))",
        expectedOutput: "7.0",
        hints: ["La media è somma diviso conteggio", "round(x, 2) arrotonda a due decimali"],
        explanation: "Il metodo della media usa la media storica come previsione costante. Funziona quando la serie oscilla attorno a un livello stabile, ma ignora completamente un eventuale trend.",
        brokenCode: "serie = [4, 6, 8, 10]\nprint(sum(serie) // len(serie))",
        debugHint: "La divisione intera tronca i decimali: qui esce 7 invece di 7.0.",
      },
      {
        titleTemplate: "Media mobile a 3",
        descTemplate: "Calcola la media mobile a 3 periodi di [2, 4, 6, 8, 10] e stampa l'ultimo valore.",
        starterCode: "import pandas as pd\n",
        solutionCode: "import pandas as pd\ns = pd.Series([2, 4, 6, 8, 10])\nprint(s.rolling(3).mean().iloc[-1])",
        expectedOutput: "8.0",
        hints: ["rolling(3) crea la finestra scorrevole", "I primi due valori restano NaN"],
        explanation: "La media mobile smorza il rumore mediando gli ultimi periodi. L'ultimo valore è la media di 6, 8 e 10, cioe' 8.0: è anche la previsione naive per il periodo successivo.",
        brokenCode: "import pandas as pd\ns = pd.Series([2, 4, 6, 8, 10])\nprint(s.rolling(3).mean().iloc[0])",
        debugHint: "Il primo valore è NaN: la finestra da 3 non è ancora piena.",
      },
      {
        titleTemplate: "Variazione periodo su periodo",
        descTemplate: "Calcola la differenza fra periodi consecutivi di [10, 13, 12] e stampa l'ultima.",
        starterCode: "import pandas as pd\n",
        solutionCode: "import pandas as pd\ns = pd.Series([10, 13, 12])\nprint(s.diff().iloc[-1])",
        expectedOutput: "-1.0",
        hints: ["diff() sottrae il valore precedente", "Il primo elemento diventa NaN"],
        explanation: "diff trasforma i livelli in variazioni. E' il primo passo per capire se una serie ha un trend: variazioni sistematicamente positive indicano crescita.",
        brokenCode: "import pandas as pd\ns = pd.Series([10, 13, 12])\nprint(s.diff().sum())",
        debugHint: "La somma delle differenze da' la variazione totale, non l'ultima variazione.",
      },
      {
        titleTemplate: "Errore di una previsione",
        descTemplate: "Il valore reale è 100, la previsione era 90. Stampa l'errore assoluto.",
        starterCode: "reale = 100\nprevisto = 90\n",
        solutionCode: "reale = 100\nprevisto = 90\nprint(abs(reale - previsto))",
        expectedOutput: "10",
        hints: ["L'errore assoluto ignora il segno", "abs() restituisce il valore assoluto"],
        explanation: "L'errore assoluto misura la distanza fra previsione e realta' senza badare alla direzione. Serve il valore assoluto perché sottostimare di 10 e sovrastimare di 10 sono errori ugualmente gravi.",
        brokenCode: "reale = 100\nprevisto = 90\nprint(reale - previsto)",
        debugHint: "Senza abs() l'errore ha un segno: sommando errori opposti si annullerebbero a vicenda.",
      },
      {
        titleTemplate: "Crescita percentuale",
        descTemplate: "Da 200 a 250: stampa la variazione percentuale arrotondata a 1 decimale.",
        starterCode: "prima = 200\ndopo = 250\n",
        solutionCode: "prima = 200\ndopo = 250\nprint(round((dopo - prima) / prima * 100, 1))",
        expectedOutput: "25.0",
        hints: ["La variazione si divide sempre per il valore di PARTENZA", "Moltiplica per 100 per avere la percentuale"],
        explanation: "Dividere per il valore di partenza è cio' che rende la variazione confrontabile fra serie di ordini di grandezza diversi. Dividere per quello di arrivo darebbe un numero diverso e privo di senso.",
        brokenCode: "prima = 200\ndopo = 250\nprint(round((dopo - prima) / dopo * 100, 1))",
        debugHint: "Il denominatore deve essere il valore di partenza, non quello di arrivo.",
      },
      {
        titleTemplate: "Ultimo valore di una serie temporale",
        descTemplate: "Data la serie indicizzata per data, stampa l'ultimo valore osservato.",
        starterCode: "import pandas as pd\n",
        solutionCode: "import pandas as pd\ns = pd.Series([5, 7, 9], index=pd.to_datetime(['2026-01-01', '2026-02-01', '2026-03-01']))\nprint(s.iloc[-1])",
        expectedOutput: "9",
        hints: ["iloc accede per posizione, loc per etichetta", "-1 è l'ultima posizione"],
        explanation: "Con un indice di date, iloc[-1] prende l'ultima osservazione in ordine di posizione. E' il valore da cui parte qualunque previsione naive.",
        brokenCode: "import pandas as pd\ns = pd.Series([5, 7, 9], index=pd.to_datetime(['2026-01-01', '2026-02-01', '2026-03-01']))\nprint(s.loc[-1])",
        debugHint: "Con un indice di date loc[-1] cerca l'ETICHETTA -1, che non esiste: serve iloc.",
      },
    ],
    [Difficulty.Medium]: [
      {
        titleTemplate: "MAE fra reale e previsto",
        descTemplate: "Reali [10, 20, 30], previsti [12, 18, 33]. Calcola l'errore assoluto medio arrotondato a 2 decimali.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nreali = np.array([10, 20, 30])\nprevisti = np.array([12, 18, 33])\nprint(round(float(np.mean(np.abs(reali - previsti))), 2))",
        expectedOutput: "2.33",
        hints: ["Prima gli errori assoluti, poi la media", "Con numpy le operazioni sono vettorizzate"],
        explanation: "Il MAE è la media degli errori assoluti ed è espresso nella stessa unita' dei dati, quindi si interpreta subito: qui sbagliamo in media 2 unita'.",
        brokenCode: "import numpy as np\nreali = np.array([10, 20, 30])\nprevisti = np.array([12, 18, 33])\nprint(np.abs(np.mean(reali - previsti)))",
        debugHint: "Media e valore assoluto sono invertiti: gli errori di segno opposto si annullano prima di essere resi positivi.",
      },
      {
        titleTemplate: "RMSE",
        descTemplate: "Con gli stessi dati, calcola la radice dell'errore quadratico medio arrotondata a 2 decimali.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nreali = np.array([10, 20, 30])\nprevisti = np.array([12, 18, 33])\nprint(round(float(np.sqrt(np.mean((reali - previsti) ** 2))), 2))",
        expectedOutput: "2.38",
        hints: ["Eleva al quadrato, media, poi radice", "L'ordine delle tre operazioni non è scambiabile"],
        explanation: "L'RMSE eleva al quadrato gli errori prima di mediarli, quindi penalizza gli errori grandi più del MAE. Se un errore grosso è molto più costoso di tanti piccoli, è la metrica giusta.",
        brokenCode: "import numpy as np\nreali = np.array([10, 20, 30])\nprevisti = np.array([12, 18, 33])\nprint(round(float(np.mean(np.sqrt((reali - previsti) ** 2))), 2))",
        debugHint: "Radice e media sono invertite: così ottieni il MAE, non l'RMSE.",
      },
      {
        titleTemplate: "MAPE",
        descTemplate: "Reali [100, 200], previsti [110, 180]. Calcola l'errore percentuale assoluto medio.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nreali = np.array([100, 200])\nprevisti = np.array([110, 180])\nprint(np.mean(np.abs((reali - previsti) / reali)) * 100)",
        expectedOutput: "10.0",
        hints: ["Ogni errore va rapportato al proprio valore reale", "Il risultato si moltiplica per 100"],
        explanation: "Il MAPE esprime l'errore in percentuale, quindi si confronta fra serie di scale diverse. Il difetto è che esplode quando un valore reale è vicino a zero.",
        brokenCode: "import numpy as np\nreali = np.array([100, 200])\nprevisti = np.array([110, 180])\nprint(np.mean(np.abs(reali - previsti) / np.mean(reali)) * 100)",
        debugHint: "Il denominatore deve essere il valore reale di OGNI punto, non la media della serie.",
      },
      {
        titleTemplate: "Divisione train e test",
        descTemplate: "Su una serie di 10 valori, tieni gli ultimi 3 come test e stampa le due lunghezze.",
        starterCode: "serie = list(range(10))\n",
        solutionCode: "serie = list(range(10))\ntrain, test = serie[:-3], serie[-3:]\nprint(len(train), len(test))",
        expectedOutput: "7 3",
        hints: ["Nelle serie storiche il test è sempre la CODA, mai un campione casuale", "Lo slicing negativo separa le due parti"],
        explanation: "Con dati temporali il test deve stare dopo il train: mescolare a caso significherebbe addestrare su dati futuri per prevedere il passato, che gonfia il risultato e non è replicabile in produzione.",
        brokenCode: "import random\nserie = list(range(10))\nrandom.shuffle(serie)\ntrain, test = serie[:-3], serie[-3:]\nprint(len(train), len(test))",
        debugHint: "Mescolare una serie storica rompe l'ordine temporale: il modello vedrebbe il futuro.",
      },
      {
        titleTemplate: "Metodo del drift",
        descTemplate: "La serie è [10, 12, 14, 16]. Prevedi il prossimo valore estendendo la pendenza media.",
        starterCode: "serie = [10, 12, 14, 16]\n",
        solutionCode: "serie = [10, 12, 14, 16]\npendenza = (serie[-1] - serie[0]) / (len(serie) - 1)\nprint(serie[-1] + pendenza)",
        expectedOutput: "18.0",
        hints: ["La pendenza media va dal primo all'ultimo punto", "Il denominatore è il numero di INTERVALLI, non di punti"],
        explanation: "Il drift prolunga la retta che unisce il primo e l'ultimo punto. Il denominatore è len-1 perché fra 4 punti ci sono 3 intervalli: usare len darebbe una pendenza sottostimata.",
        brokenCode: "serie = [10, 12, 14, 16]\npendenza = (serie[-1] - serie[0]) / len(serie)\nprint(serie[-1] + pendenza)",
        debugHint: "Il denominatore giusto è len-1: gli intervalli sono uno in meno dei punti.",
      },
      {
        titleTemplate: "Media mobile come previsione",
        descTemplate: "Prevedi il prossimo valore di [10, 12, 14, 20] con la media degli ultimi 2 periodi.",
        starterCode: "serie = [10, 12, 14, 20]\n",
        solutionCode: "serie = [10, 12, 14, 20]\nfinestra = serie[-2:]\nprint(sum(finestra) / len(finestra))",
        expectedOutput: "17.0",
        hints: ["Lo slicing -2: prende gli ultimi due", "La previsione è la loro media"],
        explanation: "Mediare solo gli ultimi periodi rende la previsione più reattiva ai cambiamenti recenti rispetto alla media di tutta la storia. Più la finestra è corta, più il modello segue il rumore.",
        brokenCode: "serie = [10, 12, 14, 20]\nfinestra = serie[:2]\nprint(sum(finestra) / len(finestra))",
        debugHint: "serie[:2] prende i PRIMI due valori: per prevedere servono gli ultimi.",
      },
      {
        titleTemplate: "Confronto fra due modelli",
        descTemplate: "Il modello A ha MAE 3.5, il modello B 2.8. Stampa quale scegli e di quanto è migliore in percentuale.",
        starterCode: "mae_a = 3.5\nmae_b = 2.8\n",
        solutionCode: "mae_a = 3.5\nmae_b = 2.8\nmigliore = 'A' if mae_a < mae_b else 'B'\nguadagno = abs(mae_a - mae_b) / max(mae_a, mae_b) * 100\nprint(f'Meglio {migliore}, {round(guadagno, 1)}% di errore in meno')",
        expectedOutput: "Meglio B, 20.0% di errore in meno",
        hints: ["Errore più BASSO significa modello migliore", "Il guadagno si rapporta al modello peggiore"],
        explanation: "Nelle metriche di errore vince il valore più basso, il contrario di accuratezza o R quadro. Rapportare la differenza al modello peggiore dice quanto errore si è eliminato.",
        brokenCode: "mae_a = 3.5\nmae_b = 2.8\nmigliore = 'A' if mae_a > mae_b else 'B'\nprint(f'Meglio {migliore}')",
        debugHint: "Il confronto è invertito: sul MAE vince chi ha il valore più basso.",
      },
    ],
    [Difficulty.Hard]: [
      {
        titleTemplate: "Naive stagionale",
        descTemplate: "Serie trimestrale [10, 20, 30, 40, 11, 21, 31, 41] con stagionalita' 4. Prevedi il prossimo valore.",
        starterCode: "serie = [10, 20, 30, 40, 11, 21, 31, 41]\nstagione = 4\n",
        solutionCode: "serie = [10, 20, 30, 40, 11, 21, 31, 41]\nstagione = 4\nprint(serie[-stagione])",
        expectedOutput: "11",
        hints: ["La naive stagionale ripete il valore dello stesso periodo del ciclo precedente", "L'indice -stagione lo raggiunge direttamente"],
        explanation: "Con stagionalita' 4, il prossimo trimestre corrisponde a quello di un anno fa: serie[-4] vale 11, cioe' il primo trimestre del ciclo precedente. E' un riferimento molto forte sui dati stagionali.",
        brokenCode: "serie = [10, 20, 30, 40, 11, 21, 31, 41]\nprint(serie[-1])",
        debugHint: "La naive semplice ignora la stagionalita': ripeterebbe 41 invece del valore dello stesso trimestre.",
      },
      {
        titleTemplate: "Trend con regressione lineare",
        descTemplate: "Adatta una retta a [2, 4, 6, 8] e prevedi il valore in posizione 4.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\ny = np.array([2, 4, 6, 8])\nx = np.arange(len(y))\nm, q = np.polyfit(x, y, 1)\nprint(round(float(m * 4 + q), 2))",
        expectedOutput: "10.0",
        hints: ["polyfit con grado 1 restituisce pendenza e intercetta", "La previsione si valuta nel punto x successivo"],
        explanation: "polyfit trova la retta che minimizza l'errore quadratico. Con una serie perfettamente lineare la pendenza è 2 e l'intercetta 2, quindi il valore in x=4 è 10.",
        brokenCode: "import numpy as np\ny = np.array([2, 4, 6, 8])\nx = np.arange(len(y))\nm, q = np.polyfit(x, y, 1)\nprint(round(float(m * len(y) + q), 2))",
        debugHint: "Qui funziona per coincidenza, ma confondere la posizione con la lunghezza rompe appena cambia l'origine dell'asse.",
      },
      {
        titleTemplate: "Backtest walk-forward",
        descTemplate: "Sulla serie [10, 11, 12, 13], usa la naive e calcola il MAE su tutte le previsioni un passo avanti.",
        starterCode: "serie = [10, 11, 12, 13]\n",
        solutionCode: "serie = [10, 11, 12, 13]\nerrori = [abs(serie[i] - serie[i-1]) for i in range(1, len(serie))]\nprint(sum(errori) / len(errori))",
        expectedOutput: "1.0",
        hints: ["Ogni previsione naive è il valore precedente", "Il primo punto non ha previsione"],
        explanation: "Il backtest walk-forward valuta il modello come se avesse previsto ogni periodo con i soli dati fino a quel momento. Per la naive l'errore coincide con la variazione periodo su periodo.",
        brokenCode: "serie = [10, 11, 12, 13]\nerrori = [abs(serie[i] - serie[i-1]) for i in range(len(serie))]\nprint(sum(errori) / len(errori))",
        debugHint: "Partendo da 0, serie[-1] è l'ultimo elemento: il primo errore risulta sbagliato.",
      },
      {
        titleTemplate: "Intervallo di previsione",
        descTemplate: "Previsione 100, deviazione standard dei residui 5. Calcola l'intervallo al 95 per cento.",
        starterCode: "previsione = 100\nsigma = 5\n",
        solutionCode: "previsione = 100\nsigma = 5\nprint(previsione - 1.96 * sigma, previsione + 1.96 * sigma)",
        expectedOutput: "90.2 109.8",
        hints: ["Al 95 per cento il moltiplicatore è 1.96", "L'intervallo è simmetrico attorno alla previsione"],
        explanation: "L'intervallo comunica l'incertezza: una previsione puntuale senza banda nasconde quanto il modello sia affidabile. Il moltiplicatore 1.96 vale per una distribuzione normale al 95 per cento.",
        brokenCode: "previsione = 100\nsigma = 5\nprint(previsione - sigma, previsione + sigma)",
        debugHint: "Con un solo sigma l'intervallo copre circa il 68 per cento, non il 95.",
      },
      {
        titleTemplate: "Destagionalizzare",
        descTemplate: "Serie [10, 20, 30, 40] con indici stagionali [0.5, 1.0, 1.5, 1.0]: rimuovi la stagionalita'.",
        starterCode: "serie = [10, 20, 30, 40]\nindici = [0.5, 1.0, 1.5, 1.0]\n",
        solutionCode: "serie = [10, 20, 30, 40]\nindici = [0.5, 1.0, 1.5, 1.0]\nprint([round(v / i, 2) for v, i in zip(serie, indici)])",
        expectedOutput: "[20.0, 20.0, 20.0, 40.0]",
        hints: ["Destagionalizzare significa DIVIDERE per l'indice", "zip accoppia i due elenchi"],
        explanation: "Dividere per l'indice stagionale rimuove l'effetto del periodo e lascia il livello di fondo, così il trend diventa leggibile. Moltiplicare farebbe l'opposto: aggiungerebbe stagionalita'.",
        brokenCode: "serie = [10, 20, 30, 40]\nindici = [0.5, 1.0, 1.5, 1.0]\nprint([round(v * i, 2) for v, i in zip(serie, indici)])",
        debugHint: "Moltiplicare AGGIUNGE stagionalita': per toglierla bisogna dividere.",
      },
      {
        titleTemplate: "Autocorrelazione a ritardo 1",
        descTemplate: "Calcola la correlazione fra la serie [1, 2, 3, 4, 5] e se stessa ritardata di 1.",
        starterCode: "import pandas as pd\n",
        solutionCode: "import pandas as pd\ns = pd.Series([1, 2, 3, 4, 5])\nprint(round(s.autocorr(lag=1), 2))",
        expectedOutput: "1.0",
        hints: ["autocorr misura quanto la serie somiglia a se stessa spostata", "Con un trend perfetto vale 1"],
        explanation: "L'autocorrelazione a ritardo 1 dice quanto ogni valore dipende dal precedente. Vicina a 1 significa serie molto prevedibile dal proprio passato, ed è il segnale che un modello autoregressivo può funzionare.",
        brokenCode: "import pandas as pd\ns = pd.Series([1, 2, 3, 4, 5])\nprint(round(s.corr(s), 2))",
        debugHint: "Correlare la serie con se stessa NON spostata da' sempre 1: manca il ritardo.",
      },
      {
        titleTemplate: "Somma progressiva del budget",
        descTemplate: "Dalla serie mensile [100, 120, 90], calcola il cumulato e stampa il totale a fine periodo.",
        starterCode: "import pandas as pd\n",
        solutionCode: "import pandas as pd\ns = pd.Series([100, 120, 90])\nprint(s.cumsum().iloc[-1])",
        expectedOutput: "310",
        hints: ["cumsum accumula progressivamente", "L'ultimo valore del cumulato è il totale"],
        explanation: "Il cumulato risponde alla domanda 'a che punto siamo rispetto al budget annuo'. L'ultimo valore coincide con la somma totale, ma la serie intera mostra anche il percorso.",
        brokenCode: "import pandas as pd\ns = pd.Series([100, 120, 90])\nprint(s.cumsum().iloc[0])",
        debugHint: "Il primo valore del cumulato è solo il primo mese, non il totale.",
      },
    ],
  },

  [PythonTopicId.DeepLearning]: {
    [Difficulty.Easy]: [
      {
        titleTemplate: "Forma di un tensore",
        descTemplate: "Crea una matrice 2x3 di numeri e stampa la sua forma.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nt = np.array([[1, 2, 3], [4, 5, 6]])\nprint(t.shape)",
        expectedOutput: "(2, 3)",
        hints: ["shape restituisce una tupla (righe, colonne)", "In PyTorch si scrive torch.tensor([[...]]).shape"],
        explanation: "La forma è la prima cosa da controllare in una rete: quasi tutti gli errori di training sono forme che non combaciano. L'equivalente PyTorch è torch.tensor(...).shape, con la stessa semantica.",
        brokenCode: "import numpy as np\nt = np.array([[1, 2, 3], [4, 5, 6]])\nprint(t.size)",
        debugHint: "size da' il numero TOTALE di elementi (6), non la forma.",
      },
      {
        titleTemplate: "Prodotto scalare",
        descTemplate: "Calcola il prodotto scalare fra [1, 2, 3] e [4, 5, 6].",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\na = np.array([1, 2, 3])\nb = np.array([4, 5, 6])\nprint(np.dot(a, b))",
        expectedOutput: "32",
        hints: ["Il prodotto scalare moltiplica elemento per elemento e somma", "In PyTorch è torch.dot(a, b)"],
        explanation: "Il prodotto scalare è l'operazione elementare di ogni neurone: pesi per ingressi, sommati. Qui vale 1*4 + 2*5 + 3*6 = 32.",
        brokenCode: "import numpy as np\na = np.array([1, 2, 3])\nb = np.array([4, 5, 6])\nprint(a * b)",
        debugHint: "L'asterisco moltiplica elemento per elemento senza sommare: restituisce un vettore, non uno scalare.",
      },
      {
        titleTemplate: "ReLU",
        descTemplate: "Applica la ReLU a [-2, 0, 3] e stampa il risultato.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nx = np.array([-2, 0, 3])\nprint(np.maximum(0, x))",
        expectedOutput: "[0 0 3]",
        hints: ["ReLU azzera i negativi e lascia passare i positivi", "In PyTorch è torch.relu(x)"],
        explanation: "La ReLU è l'attivazione più usata: introduce non linearita' con una sola operazione e non satura sui valori grandi, il che rende l'addestramento più stabile.",
        brokenCode: "import numpy as np\nx = np.array([-2, 0, 3])\nprint(np.max(0, x))",
        debugHint: "np.max riduce a un solo valore; per il confronto elemento per elemento serve np.maximum.",
      },
      {
        titleTemplate: "Sigmoide",
        descTemplate: "Calcola la sigmoide di 0 e stampala.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nprint(1 / (1 + np.exp(-0)))",
        expectedOutput: "0.5",
        hints: ["La formula è 1 / (1 + e^-x)", "In 0 la sigmoide vale esattamente 0.5"],
        explanation: "La sigmoide schiaccia qualunque numero fra 0 e 1, quindi si legge come una probabilita'. In zero vale 0.5, il punto di massima incertezza.",
        brokenCode: "import numpy as np\nprint(1 / (1 + np.exp(0)))",
        debugHint: "Manca il segno meno nell'esponente: la formula è 1/(1+e^-x).",
      },
      {
        titleTemplate: "Moltiplicazione di matrici",
        descTemplate: "Moltiplica una matrice 2x3 per una 3x1 e stampa la forma del risultato.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nW = np.ones((2, 3))\nx = np.ones((3, 1))\nprint((W @ x).shape)",
        expectedOutput: "(2, 1)",
        hints: ["Le dimensioni interne devono combaciare", "Il risultato ha la forma (righe della prima, colonne della seconda)"],
        explanation: "In una rete ogni strato è una moltiplicazione di matrici. La regola delle dimensioni (2x3 per 3x1 da' 2x1) è quella che decide quanti neuroni può avere ogni strato.",
        brokenCode: "import numpy as np\nW = np.ones((2, 3))\nx = np.ones((3, 1))\nprint((x @ W).shape)",
        debugHint: "L'ordine conta: 3x1 per 2x3 non è una moltiplicazione valida.",
      },
      {
        titleTemplate: "Somma per righe",
        descTemplate: "Somma gli elementi di una matrice 2x2 lungo le righe e stampa il risultato.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nt = np.array([[1, 2], [3, 4]])\nprint(t.sum(axis=1))",
        expectedOutput: "[3 7]",
        hints: ["axis=1 riduce lungo le colonne, restituendo un valore per riga", "In PyTorch è t.sum(dim=1)"],
        explanation: "Capire gli assi è meta' del lavoro con i tensori: axis=1 collassa le colonne e lascia una somma per riga. PyTorch usa dim al posto di axis, ma la logica è identica.",
        brokenCode: "import numpy as np\nt = np.array([[1, 2], [3, 4]])\nprint(t.sum(axis=0))",
        debugHint: "axis=0 somma lungo le righe e da' un valore per COLONNA: [4 6] invece di [3 7].",
      },
      {
        titleTemplate: "Cambiare forma",
        descTemplate: "Trasforma un vettore di 6 elementi in una matrice 2x3 e stampane la forma.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nv = np.arange(6)\nprint(v.reshape(2, 3).shape)",
        expectedOutput: "(2, 3)",
        hints: ["Il numero totale di elementi deve restare lo stesso", "In PyTorch è t.view(2, 3) o t.reshape(2, 3)"],
        explanation: "reshape riorganizza gli stessi dati in una forma diversa: 6 elementi entrano in una 2x3 perché 2 per 3 fa 6. E' l'operazione che serve per passare da un batch appiattito a uno strutturato.",
        brokenCode: "import numpy as np\nv = np.arange(6)\nprint(v.reshape(4, 2).shape)",
        debugHint: "6 elementi non entrano in una 4x2: reshape solleva un errore se il totale non combacia.",
      },
      {
        titleTemplate: "Trasposta",
        descTemplate: "Stampa la forma della trasposta di una matrice 2x3.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nt = np.ones((2, 3))\nprint(t.T.shape)",
        expectedOutput: "(3, 2)",
        hints: ["La trasposta scambia righe e colonne", "In PyTorch è t.T oppure t.transpose(0, 1)"],
        explanation: "La trasposta serve continuamente nella retropropagazione, dove i gradienti risalgono la rete attraverso i pesi trasposti. Una 2x3 diventa una 3x2.",
        brokenCode: "import numpy as np\nt = np.ones((2, 3))\nprint(t.shape)",
        debugHint: "Manca .T: stampi la forma originale invece di quella trasposta.",
      },
      {
        titleTemplate: "Tangente iperbolica",
        descTemplate: "Calcola la tanh di 0 e stampala.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nprint(np.tanh(0))",
        expectedOutput: "0.0",
        hints: ["La tanh è centrata in zero", "In PyTorch è torch.tanh(x)"],
        explanation: "La tanh schiaccia i valori fra -1 e 1 ed è centrata in zero, il che aiuta la convergenza rispetto alla sigmoide. In zero vale esattamente 0.",
        brokenCode: "import numpy as np\nprint(np.tan(0))",
        debugHint: "np.tan è la tangente trigonometrica, non la tangente IPERBOLICA: serve np.tanh.",
      },
    ],
    [Difficulty.Medium]: [
      {
        titleTemplate: "Passaggio in avanti di uno strato",
        descTemplate: "Con pesi [[1, 1], [2, 2]], ingresso [1, 1] e bias [0, 1], calcola l'uscita dello strato.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nW = np.array([[1, 1], [2, 2]])\nx = np.array([1, 1])\nb = np.array([0, 1])\nprint(W @ x + b)",
        expectedOutput: "[2 5]",
        hints: ["Prima la moltiplicazione, poi la somma del bias", "In PyTorch lo fa nn.Linear"],
        explanation: "Questo è esattamente cio' che calcola nn.Linear: pesi per ingressi più bias. Tutto il resto di una rete è questa operazione ripetuta e intervallata da attivazioni.",
        brokenCode: "import numpy as np\nW = np.array([[1, 1], [2, 2]])\nx = np.array([1, 1])\nb = np.array([0, 1])\nprint(W @ (x + b))",
        debugHint: "Il bias si somma DOPO la moltiplicazione, non all'ingresso.",
      },
      {
        titleTemplate: "Errore quadratico medio",
        descTemplate: "Previsioni [2.0, 3.0], valori veri [1.0, 5.0]. Calcola la MSE.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\ny = np.array([1.0, 5.0])\np = np.array([2.0, 3.0])\nprint(np.mean((p - y) ** 2))",
        expectedOutput: "2.5",
        hints: ["Eleva al quadrato le differenze, poi media", "In PyTorch è nn.MSELoss()"],
        explanation: "La MSE è la funzione di perdita standard per la regressione. Il quadrato la rende derivabile ovunque e penalizza gli errori grandi, che è cio' che permette alla discesa del gradiente di funzionare.",
        brokenCode: "import numpy as np\ny = np.array([1.0, 5.0])\np = np.array([2.0, 3.0])\nprint(np.mean(p - y) ** 2)",
        debugHint: "Le parentesi sono sbagliate: così elevi al quadrato la media invece di mediare i quadrati.",
      },
      {
        titleTemplate: "Softmax",
        descTemplate: "Applica la softmax a [1.0, 1.0] e stampa il risultato arrotondato a 2 decimali.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nz = np.array([1.0, 1.0])\ne = np.exp(z - np.max(z))\nprint(np.round(e / e.sum(), 2))",
        expectedOutput: "[0.5 0.5]",
        hints: ["Sottrarre il massimo evita l'overflow senza cambiare il risultato", "Le uscite sommano sempre a 1"],
        explanation: "La softmax trasforma punteggi arbitrari in probabilita' che sommano a 1. Con due valori uguali il risultato è 0.5 e 0.5. Sottrarre il massimo è un accorgimento numerico che PyTorch applica internamente.",
        brokenCode: "import numpy as np\nz = np.array([1.0, 1.0])\nprint(np.round(np.exp(z) / len(z), 2))",
        debugHint: "Il denominatore deve essere la SOMMA degli esponenziali, non il numero di elementi.",
      },
      {
        titleTemplate: "Gradiente numerico",
        descTemplate: "Stima la derivata di f(x) = x^2 in x=3 con il rapporto incrementale e arrotonda a 2 decimali.",
        starterCode: "def f(x):\n    return x ** 2\n",
        solutionCode: "def f(x):\n    return x ** 2\n\nh = 1e-5\nx = 3\nprint(round((f(x + h) - f(x - h)) / (2 * h), 2))",
        expectedOutput: "6.0",
        hints: ["La differenza centrata è più precisa di quella in avanti", "La derivata di x^2 in 3 vale 6"],
        explanation: "La differenza centrata approssima la derivata valutando la funzione poco prima e poco dopo il punto. E' così che si verifica a mano che l'autograd di PyTorch calcoli i gradienti giusti.",
        brokenCode: "def f(x):\n    return x ** 2\n\nh = 1e-5\nx = 3\nprint(round((f(x + h) - f(x)) / h, 2))",
        debugHint: "La differenza in avanti è meno precisa: introduce un errore di ordine h invece di h al quadrato.",
      },
      {
        titleTemplate: "Un passo di discesa del gradiente",
        descTemplate: "Parametro 5.0, gradiente 2.0, passo di apprendimento 0.1. Calcola il nuovo valore.",
        starterCode: "peso = 5.0\ngradiente = 2.0\nlr = 0.1\n",
        solutionCode: "peso = 5.0\ngradiente = 2.0\nlr = 0.1\nprint(peso - lr * gradiente)",
        expectedOutput: "4.8",
        hints: ["Ci si muove nella direzione OPPOSTA al gradiente", "In PyTorch lo fa optimizer.step()"],
        explanation: "Il gradiente indica la direzione di massima crescita della perdita, quindi per ridurla ci si muove in senso opposto. Il segno meno è tutta la discesa del gradiente.",
        brokenCode: "peso = 5.0\ngradiente = 2.0\nlr = 0.1\nprint(peso + lr * gradiente)",
        debugHint: "Con il più sali lungo il gradiente e la perdita aumenta invece di diminuire.",
      },
      {
        titleTemplate: "Broadcasting del bias",
        descTemplate: "Somma un bias [1, 2] a un batch 2x2 e stampa il risultato.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nX = np.array([[10, 20], [30, 40]])\nb = np.array([1, 2])\nprint(X + b)",
        expectedOutput: "[[11 22]\n [31 42]]",
        hints: ["numpy estende automaticamente il vettore su tutte le righe", "Serve che l'ultima dimensione combaci"],
        explanation: "Il broadcasting somma lo stesso bias a ogni riga del batch senza scriverne il ciclo. E' il motivo per cui un bias di 2 elementi basta per un batch di qualunque dimensione.",
        brokenCode: "import numpy as np\nX = np.array([[10, 20], [30, 40]])\nb = np.array([1, 2, 3])\nprint(X + b)",
        debugHint: "Un bias di 3 elementi non si allinea con 2 colonne: il broadcasting fallisce.",
      },
      {
        titleTemplate: "Accuratezza di una classificazione",
        descTemplate: "Previsioni [1, 0, 1, 1], etichette [1, 0, 0, 1]. Calcola l'accuratezza.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\np = np.array([1, 0, 1, 1])\ny = np.array([1, 0, 0, 1])\nprint((p == y).mean())",
        expectedOutput: "0.75",
        hints: ["Il confronto da' un array di booleani", "La media dei booleani è la frazione di corretti"],
        explanation: "In numpy i booleani valgono 0 e 1, quindi la loro media è direttamente la percentuale di previsioni corrette. Qui 3 su 4, cioe' 0.75.",
        brokenCode: "import numpy as np\np = np.array([1, 0, 1, 1])\ny = np.array([1, 0, 0, 1])\nprint((p == y).sum())",
        debugHint: "sum conta i corretti (3) invece di dare la frazione: serve mean.",
      },
      {
        titleTemplate: "Classe prevista dalla softmax",
        descTemplate: "Dai punteggi [0.1, 0.7, 0.2], stampa l'indice della classe più probabile.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\np = np.array([0.1, 0.7, 0.2])\nprint(np.argmax(p))",
        expectedOutput: "1",
        hints: ["argmax restituisce la POSIZIONE del massimo", "In PyTorch è torch.argmax(p)"],
        explanation: "La softmax da' le probabilita', argmax le trasforma in una decisione restituendo l'indice della classe più probabile. E' l'ultimo passo di ogni classificatore.",
        brokenCode: "import numpy as np\np = np.array([0.1, 0.7, 0.2])\nprint(np.max(p))",
        debugHint: "max da' il VALORE massimo (0.7), non l'indice della classe: serve argmax.",
      },
      {
        titleTemplate: "Derivata della ReLU",
        descTemplate: "Calcola la derivata della ReLU nei punti [-2, 3] e stampala.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\nx = np.array([-2, 3])\nprint((x > 0).astype(int))",
        expectedOutput: "[0 1]",
        hints: ["La derivata vale 0 sui negativi e 1 sui positivi", "Il confronto produce booleani da convertire in interi"],
        explanation: "La derivata della ReLU è una porta: lascia passare il gradiente dove l'ingresso era positivo e lo blocca altrove. E' anche il motivo dei neuroni morti, quelli sempre negativi che non ricevono più gradiente.",
        brokenCode: "import numpy as np\nx = np.array([-2, 3])\nprint(np.maximum(0, x))",
        debugHint: "Questa è la ReLU stessa, non la sua derivata: la derivata è 0 o 1.",
      },
    ],
    [Difficulty.Hard]: [
      {
        titleTemplate: "Retropropagazione su un neurone",
        descTemplate: "Con x=2, w=3, target=10 e uscita y=w*x, calcola il gradiente della MSE rispetto a w.",
        starterCode: "x = 2\nw = 3\ntarget = 10\n",
        solutionCode: "x = 2\nw = 3\ntarget = 10\ny = w * x\nperdita_grad = 2 * (y - target)\nprint(perdita_grad * x)",
        expectedOutput: "-16",
        hints: ["La regola della catena moltiplica le due derivate", "La derivata di y rispetto a w è x"],
        explanation: "La derivata della perdita rispetto a w è 2*(y - target) moltiplicato per x, cioe' la regola della catena applicata a due passaggi. Qui y=6, quindi il gradiente è 2*(-4)*2 = -16: negativo, quindi w va aumentato.",
        brokenCode: "x = 2\nw = 3\ntarget = 10\ny = w * x\nprint(2 * (y - target))",
        debugHint: "Manca il fattore x della regola della catena: quello è il gradiente rispetto a y, non a w.",
      },
      {
        titleTemplate: "Ciclo di addestramento",
        descTemplate: "Addestra w partendo da 0 per imparare y = 2x su x=1, con passo 0.1 per 10 iterazioni. Stampa w arrotondato a 3 decimali.",
        starterCode: "w = 0.0\nlr = 0.1\n",
        solutionCode: "w = 0.0\nlr = 0.1\nx, target = 1.0, 2.0\nfor _ in range(10):\n    y = w * x\n    grad = 2 * (y - target) * x\n    w -= lr * grad\nprint(round(w, 3))",
        expectedOutput: "1.785",
        hints: ["Ogni giro: previsione, gradiente, aggiornamento", "Il parametro converge verso 2"],
        explanation: "Questo è il ciclo di addestramento completo in cinque righe: passaggio in avanti, gradiente, aggiornamento. PyTorch lo scrive come loss.backward() seguito da optimizer.step(), ma la matematica sotto è questa.",
        brokenCode: "w = 0.0\nlr = 0.1\nx, target = 1.0, 2.0\nfor _ in range(10):\n    y = w * x\n    grad = 2 * (y - target) * x\n    w += lr * grad\nprint(round(w, 3))",
        debugHint: "Con il più il parametro diverge invece di convergere: l'aggiornamento va nella direzione opposta al gradiente.",
      },
      {
        titleTemplate: "Entropia incrociata binaria",
        descTemplate: "Etichetta vera 1, probabilita' prevista 0.9. Calcola la perdita arrotondata a 4 decimali.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\ny = 1\np = 0.9\nprint(round(float(-(y * np.log(p) + (1 - y) * np.log(1 - p))), 4))",
        expectedOutput: "0.1054",
        hints: ["Solo uno dei due termini sopravvive quando l'etichetta è 0 o 1", "Il segno meno davanti è parte della formula"],
        explanation: "Con etichetta 1 resta solo -log(p): più la probabilita' prevista si avvicina a 1, più la perdita tende a zero. E' la perdita standard per la classificazione binaria, nn.BCELoss in PyTorch.",
        brokenCode: "import numpy as np\ny = 1\np = 0.9\nprint(round(float(y * np.log(p) + (1 - y) * np.log(1 - p)), 4))",
        debugHint: "Manca il segno meno: la perdita risulta negativa, mentre deve essere sempre positiva.",
      },
      {
        titleTemplate: "Media su un mini-batch",
        descTemplate: "Calcola la MSE media su un batch di 3 esempi (previsioni [1, 2, 3], veri [1, 3, 5]) arrotondata a 2 decimali.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\np = np.array([1.0, 2.0, 3.0])\ny = np.array([1.0, 3.0, 5.0])\nprint(round(float(np.mean((p - y) ** 2)), 2))",
        expectedOutput: "1.67",
        hints: ["La perdita del batch è la media di quelle dei singoli esempi", "Così il gradiente non dipende dalla dimensione del batch"],
        explanation: "Mediare invece di sommare rende il gradiente indipendente dalla dimensione del batch, quindi si può cambiare il batch senza ritoccare il passo di apprendimento. E' il comportamento predefinito di PyTorch.",
        brokenCode: "import numpy as np\np = np.array([1.0, 2.0, 3.0])\ny = np.array([1.0, 3.0, 5.0])\nprint(np.sum((p - y) ** 2))",
        debugHint: "Sommando invece di mediare, il gradiente cresce con la dimensione del batch.",
      },
      {
        titleTemplate: "Inizializzazione dei pesi",
        descTemplate: "Con seme 0, inizializza una matrice 2x2 secondo Xavier per 4 ingressi e stampane la forma.",
        starterCode: "import numpy as np\nnp.random.seed(0)\n",
        solutionCode: "import numpy as np\nnp.random.seed(0)\nn_in = 4\nW = np.random.randn(2, 2) * np.sqrt(1 / n_in)\nprint(W.shape)",
        expectedOutput: "(2, 2)",
        hints: ["Xavier scala i pesi in base al numero di ingressi", "La scala è la radice di 1/n_in"],
        explanation: "Scalare i pesi iniziali con la radice di 1/n_in mantiene costante la varianza del segnale attraverso gli strati, evitando che i gradienti esplodano o svaniscano nelle reti profonde. PyTorch offre nn.init.xavier_uniform_.",
        brokenCode: "import numpy as np\nnp.random.seed(0)\nW = np.zeros((2, 2))\nprint(W.shape)",
        debugHint: "Inizializzando tutto a zero ogni neurone calcola la stessa cosa e la rete non impara: serve una rottura di simmetria casuale.",
      },
      {
        titleTemplate: "Discesa del gradiente con due parametri",
        descTemplate: "Impara y = 2x + 1 da x=1, target=3, partendo da w=0 e b=0, passo 0.1 per 20 giri. Stampa w e b arrotondati a 2 decimali.",
        starterCode: "w, b = 0.0, 0.0\nlr = 0.1\n",
        solutionCode: "w, b = 0.0, 0.0\nlr = 0.1\nx, target = 1.0, 3.0\nfor _ in range(20):\n    y = w * x + b\n    d = 2 * (y - target)\n    w -= lr * d * x\n    b -= lr * d\nprint(round(w, 2), round(b, 2))",
        expectedOutput: "1.5 1.5",
        hints: ["Ogni parametro ha il proprio gradiente", "Il gradiente su b non è moltiplicato per x"],
        explanation: "Il gradiente rispetto a w porta il fattore x della regola della catena, quello rispetto a b no perché la derivata di b rispetto a se stesso è 1. Con un solo esempio i due parametri restano uguali fra loro.",
        brokenCode: "w, b = 0.0, 0.0\nlr = 0.1\nx, target = 1.0, 3.0\nfor _ in range(20):\n    y = w * x + b\n    d = 2 * (y - target)\n    w -= lr * d * x\n    b -= lr * d * x\nprint(round(w, 2), round(b, 2))",
        debugHint: "Qui funziona solo perché x vale 1: il gradiente su b non va moltiplicato per x.",
      },
      {
        titleTemplate: "Passo con momento",
        descTemplate: "Velocita' iniziale 0, gradiente 2.0, momento 0.9, passo 0.1. Calcola i primi due aggiornamenti del peso partendo da 1.0.",
        starterCode: "peso = 1.0\nv = 0.0\n",
        solutionCode: "peso = 1.0\nv = 0.0\ngrad, mom, lr = 2.0, 0.9, 0.1\nfor _ in range(2):\n    v = mom * v + grad\n    peso -= lr * v\nprint(round(peso, 3))",
        expectedOutput: "0.42",
        hints: ["La velocita' accumula i gradienti passati", "Il peso si aggiorna con la velocita', non con il gradiente puro"],
        explanation: "Il momento accumula la direzione dei gradienti precedenti, accelerando dove la discesa è costante e smorzando le oscillazioni. Al secondo giro la velocita' è già 3.8 invece di 2.",
        brokenCode: "peso = 1.0\nv = 0.0\ngrad, mom, lr = 2.0, 0.9, 0.1\nfor _ in range(2):\n    v = mom * v + grad\n    peso -= lr * grad\nprint(round(peso, 3))",
        debugHint: "L'aggiornamento usa il gradiente puro invece della velocita': il momento non ha alcun effetto.",
      },
      {
        titleTemplate: "Dropout in addestramento",
        descTemplate: "Con seme 5 e probabilita' 0.5, applica il dropout a un vettore di 4 uni e stampa quanti elementi sopravvivono.",
        starterCode: "import numpy as np\nnp.random.seed(5)\n",
        solutionCode: "import numpy as np\nnp.random.seed(5)\nx = np.ones(4)\nmaschera = (np.random.rand(4) > 0.5).astype(float)\nprint(int((x * maschera).sum()))",
        expectedOutput: "2",
        hints: ["La maschera casuale azzera una parte dei neuroni", "Il dropout si applica solo in addestramento, mai in valutazione"],
        explanation: "Il dropout spegne a caso una frazione di neuroni a ogni passo, costringendo la rete a non dipendere da singole unita'. Con questo seme due dei quattro neuroni vengono spenti. In fase di valutazione va disattivato, che è cio' che fa model.eval() in PyTorch.",
        brokenCode: "import numpy as np\nnp.random.seed(5)\nx = np.ones(4)\nmaschera = np.random.rand(4)\nprint(int((x * maschera).sum()))",
        debugHint: "Senza la soglia la maschera non è fatta di zeri e uni: scala i valori invece di spegnerli.",
      },
      {
        titleTemplate: "Norma del gradiente",
        descTemplate: "Calcola la norma L2 del gradiente [3.0, 4.0] e di' se supera la soglia di clipping 1.0.",
        starterCode: "import numpy as np\n",
        solutionCode: "import numpy as np\ng = np.array([3.0, 4.0])\nnorma = np.linalg.norm(g)\nprint(norma, norma > 1.0)",
        expectedOutput: "5.0 True",
        hints: ["La norma L2 è la radice della somma dei quadrati", "Il clipping scatta quando la norma supera la soglia"],
        explanation: "La norma L2 di [3, 4] è 5, il classico triangolo 3-4-5. Superata la soglia si riscala il gradiente per riportarlo alla norma massima: è il clipping che evita l'esplosione dei gradienti nelle reti ricorrenti.",
        brokenCode: "import numpy as np\ng = np.array([3.0, 4.0])\nprint(g.sum(), g.sum() > 1.0)",
        debugHint: "La somma (7.0) non è la norma: serve la radice della somma dei quadrati.",
      },
    ],
  },
};
